### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by lorenzo774** [Dharmik48/meme-generator#12]
Remove browse button and add the browse functionality to the title "[trollface] Memeracle".
Fix the "random meme" button in the header, this button open a random meme only in the browse page.

**Comment by Dharmik48** [comment]
Yeah, we can make the title the browse button that's a good idea. But I think ee should keep the `Random Meme` button as it is.

What are your thoughts?

**Comment by lorenzo774** [comment]
I think the ```Random Meme``` button in the header is a good idea, but when you open a meme you have 2 ```Random Meme``` buttons.

**Comment by Dharmik48** [comment]
Yeah that is true, but I think that's not a big deal so we can just keep the `Random Meme` in the header as it is.

**Comment by lorenzo774** [comment]
Ok, I'll work on it.

**Comment by lorenzo774** [comment]
I did not removed any ```Random Meme``` button: https://github.com/Dharmik48/meme-generator/pull/13

**Comment by MahirMahdi** [comment]
I think the color contrast isn't coherent,it can be improved especially the footer. The pagination font is only visible while hovering.

**Comment by Dharmik48** [comment]
Closed with #13

**Comment by Dharmik48** [comment]
> I think the color contrast isn't coherent,it can be improved especially the footer. The pagination font is only visible while hovering.

Hey @Mahir1015, why don't you create a new [Issue](https://github.com/Dharmik48/meme-generator/issues/new) for it? And you can work on it if you like.

**Comment by MahirMahdi** [comment]
@Dharmik48 I've created an issue for it as you've asked me to. Now I would like to work on it. So can you please assign it to me?
