### ISSUE TITLE
Fix random meme button bug in meme page

### ISSUE THREAD

**Issue by lorenzo774** [Dharmik48/meme-generator#14]
Sometimes when you click the ```Random meme``` button in the meme page the app crashes.
![img](https://i.imgur.com/uPp4CyM.png)

**Comment by abhishinde24** [comment]
I am interested working on it, can you please assign it to me

**Comment by lorenzo774** [comment]
@Dharmik48

**Comment by MahirMahdi** [comment]
Is this issue still open? I'm interested  in working on it, can you please assign it to me?

**Comment by lorenzo774** [comment]
I can't assign issues, we need @Dharmik48.

**Comment by Dharmik48** [comment]
Let's assign this to @abhishinde24.

And @Mahir1015, please see [this comment](https://github.com/Dharmik48/meme-generator/issues/12#issuecomment-1203911961).

**Comment by abhishinde24** [comment]
I searched for it, this error is due to plugin install(right click enable). if you uninstall the plugin it will work fine.

**Comment by Dharmik48** [comment]
Ya, I think that is the issue too.

Let's close this.
