### ISSUE TITLE
Improve User Experience

### ISSUE THREAD

**Issue by MahirMahdi** [Dharmik48/meme-generator#18]
The color contrast and fonts need to be improved and coherent.

**Comment by Dharmik48** [comment]
I have assigned you to @Mahir1015

**Comment by MahirMahdi** [comment]
@Dharmik48 I've made a PR for the changed font color. You can close it now.

**Comment by Dharmik48** [comment]
Yeah I saw your PR and merged it, good job🚀

**Comment by Dharmik48** [comment]
Closed with #23
