### ISSUE TITLE
Add text boxes to memes based on the imgflip API

### ISSUE THREAD

**Issue by lorenzo774** [Dharmik48/meme-generator#22]
![img](https://i.imgur.com/XBksoyS.png)

**Comment by MahirMahdi** [comment]
Did you mean to have text boxes equal to box count?

**Comment by Dharmik48** [comment]
Yeah, I was also planning to add this issue. 

It's a big problem as not all the memes have only 2 text boxes.

**Comment by MahirMahdi** [comment]
Can you assign it to me @Dharmik48 ?

**Comment by Dharmik48** [comment]
Alright, good to see you are interested in it @Mahir1015! 

I will assign this to you🚀
