### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/meme-generator#3]
The current README.md is very lame, doesn't have any proper instructions regarding the project. So we need to add those.

Some of the sections that need to added are Contribution, Install steps, Description, Screenshots, etc.

**Comment by kadeesterline** [comment]
Do you have any kind of contribution guidelines set? I would like to claim this and start working on it, I just want to make sure I'm following the right steps.

**Comment by Dharmik48** [comment]
I don't have any proper guidelines yet, but you can go to work on this as you like!

**Comment by kadeesterline** [comment]
Awesome, I'll get started!

**Comment by kadeesterline** [comment]
Just opened a PR for this, #6 adds some installation steps, adds screenshot examples and does some editing to the README. Let me know if more needs to be changed.

**Comment by Dharmik48** [comment]
Closed with #6
