### ISSUE TITLE
Add Issue templates

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/meme-generator#31]
We want to add issue templates to [this repo](https://github.com/Dharmik48/notes-react-firebase-v2.0/tree/master/.github/ISSUE_TEMPLATE) similar to this repo

**Comment by MahirMahdi** [comment]
@Dharmik48 can you please assign it to me?

**Comment by Dharmik48** [comment]
Sure, I have assigned you :)

**Comment by MahirMahdi** [comment]
@Dharmik48 do I have to make some changes or the issue templates of that repo will be fine?

**Comment by Dharmik48** [comment]
> @Dharmik48 do I have to make some changes or the issue templates of that repo will be fine?

It's fine if just add the same templates as that repo.

**Comment by Dharmik48** [comment]
Closed with #32
