### ISSUE TITLE
New search feature

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/meme-generator#4]
We should add a new search bar to search for meme templates on the website

**Comment by SethY8s** [comment]
Does the API you are using have a search feature implemented, or are we going to have to get creative???

**Comment by Dharmik48** [comment]
I am not sure if the API provides search feature so I guess we'll have to get creative!

**Comment by SethY8s** [comment]
Awesome, I've never worked with ElasticSearch, or any other search library, but I'll give it a go, and if I have something working I'll give you a pull request 👍.

**Comment by Dharmik48** [comment]
Yeah, sure! I will assign this to you.

**Comment by SethY8s** [comment]
Think I have a basic version ready! do you want all the memes or just the 25 that are displayed on the page?

**Comment by Dharmik48** [comment]
I think we can get all the memes.

**Comment by Dharmik48** [comment]
Closed with #7
