### ISSUE TITLE
Add pagination to browse page

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/meme-generator#5]
Currently, the browse page only shows 25 memes at a time, it would be better is there were a pagination system, so we can organize and show more memes

**Comment by lorenzo774** [comment]
Hi @Dharmik48 I would like to contribute by working on the pagination system.
Can you please assign this issue to me?

**Comment by Dharmik48** [comment]
Alright, I will assign this to you🚀

**Comment by Dharmik48** [comment]
Closed with #10
